server:
  port: 8080

security:
  jwt:
    secret-key: HelloWorldefqefqkejnqdrboqdodvmwfewrghytrdfwfr4wr434qeifqefnjkef
spring:
  application:
    name: quiz
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com/sql12742432
    username: sql12742432
    password: X5M86g2nMR
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  liquibase:
    change-log: classpath:/liquibase/master.xml
    database-change-log-lock-table: databasechangelock
  main:
    allow-bean-definition-overriding: true
#  logging:
#    level:
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
